cucapra/filament

src/core/component.rs, src/interval_checking/checker.rs, src/interval_checking/context.rs, tests/errors/invoke-max-trig-too-often.expect, tests/errors/invoke-max-trig-too-often.fil, tests/errors/invoke-trig-too-often.expect, tests/errors/invoke-trig-too-often.fil
An `@interface` specification requires that the binding provided to it may not pulse more often than the delay on the `@interface` itself
=> check that `@interface` specifications are obeyed by invokes

primitives/core.fil, primitives/core.sv, src/interval_checking/checker.rs, tests/check/max.fil, tests/check/merge.fil, tests/check/pipeline-with-ii-1.fil, tests/check/reg-dyanmic-use.fil, tests/errors/unprovable-cons.fil, tests/errors/unsatisfied-requirement.expect
Defines another event variable so that we can specify the delay of the register more precisely. The syntax and usage is kind of annoying so hopefully we can add some sugar for it in the future.
=> Use hack to define shorter delay for register

src/core/constraint.rs, src/utils/solver.rs, tests/errors/conflicting-use.expect, tests/errors/dynamic-share.expect, tests/errors/invalid-interface-input.expect, tests/errors/invalid-interface-output.expect, tests/errors/invoke-trig-too-often.expect, tests/errors/poly-mismatch.expect, tests/errors/unprovable-cons.expect, tests/errors/unsatisfied-guarantee.expect, tests/errors/unsatisfied-requirement.expect
Only show relevant variables when generating assignments for a failing constraints. Also use rsmt2's activation literals trick.
=> Solver improvements

evaluation/iterative-divider/harness.fil, evaluation/iterative-divider/iter-div.fil, primitives/state.fil, primitives/state.sv, src/binding/prog.rs, src/core/control.rs, src/main.rs, src/passes/bind_check.rs, src/passes/interval_checking/checker.rs, src/passes/interval_checking/context.rs, src/passes/lower.rs, src/passes/mod.rs, src/passes/monomorphize.rs, src/visitor/visit.rs, tests/errors/bundle.expect, tests/errors/poly-mismatch.expect, tests/errors/poly-mismatch.fil, tools/vscode/syntaxes/filament.tmLanguage.json
Completes the implementation of the `bundle` construct which allow exchanging information across loop boundaries. We need to implement a separate linearity check sometime in the future to ensure all locations of bundle are written to (and more generally, all outputs to a component have an assignment). 
This also allows us to implement the shift register primitive `Shift` directly inside Filament and write down parameterized implementations of the various dividers.
=> Monomorphize bundles

Cargo.toml, doc/docs/start.md
Use versions Calyx crate from crates.io to avoid random breakage from mainline Calyx changing
=> Pin calyx crate versions

primitives/reshape.fil, src/backend/compile.rs, src/binding/comp.rs, src/core/component.rs, src/core/control.rs, src/core/mod.rs, src/frontend/parser.rs, src/frontend/syntax.pest, src/passes/bind_check.rs, src/passes/bundle_elim.rs, src/passes/interval_checking/checker.rs, src/passes/monomorphize/mono.rs, src/passes/monomorphize/rewriter.rs, src/utils/post_order.rs, src/visitor/checker.rs, src/visitor/visit.rs, tools/vscode/syntaxes/filament.tmLanguage.json
Unlike an `assume`, an `assert` is statically checked by the compiler. They are mostly useful as proof hints to make the type checking be faster for complex components.
=> Add checked `assert` statement

src/ast/component.rs, src/ast/control.rs, src/backend/compile.rs, src/binding/comp.rs, src/frontend/parser.rs, src/frontend/syntax.pest, src/main.rs, src/passes/bundle_elim.rs, src/passes/dump_interface.rs, src/passes/lower.rs, src/passes/monomorphize/mono.rs, src/passes/monomorphize/rewriter.rs, src/utils/post_order.rs, src/visitor/checker.rs, src/visitor/visit.rs, tests/errors/invoke-trig-too-often.expect, tests/errors/invoke-trig-too-often.fil
Don't parse `fsm` and `invoke` constructs (these are now considered virtual constructs and only used internally for compilation) and make FSMs a field on components instead of a command.
=> Simplify AST a bit

Cargo.toml, src/ir/comp.rs, src/ir/control.rs, src/ir/fact.rs, src/ir/from_ast/astconv.rs, src/ir/from_ast/build_ctx.rs, src/ir/idxs.rs, src/ir/info.rs, src/ir/mod.rs, src/ir/printer.rs, src/ir/structure.rs, src/ir_passes/discharge.rs, src/ir_passes/hoist_facts.rs, src/ir_passes/interval_check.rs, src/ir_passes/type_check.rs, src/utils/position.rs
Uses the solver to get an assignment that demonstrates that the assert is false.
=> Print assignments demonstrating false `assert`s

src/ir/printer.rs
Exprs were getting printed in the IR as `%e0` (and so on), so now we print what they actually are. Some examples:
1. In a component signature, we were previously printing `comp %comp1[...]<%ev0: %e0>(...)`, but now it looks like `comp %comp1[...]<%ev0: 1>(...)` (or whatever the delay of the event is). The same change happens in component bodies, where we print out events.
2. In instantiations, we were previously printing `%inst0 = instance %comp0[%e0];`, but now it looks like `%inst0 = instance %comp0[#W];`.
=> Explicitly print expressions in IR printer

reticle/.gitignore
Very small pull request, data.json is automatically generated by runt and not gitignored at the moment.
=> add gitignore for data.json in reticle

src/cmdline.rs
Fixes a minor typo of falsify.
> Just touring the code base after watching the excellent recent talk from @rachitnigam. Noticed this tiny one and thought I would get my feet wet with the contribution flow :) Excited by the direction of filament and looking forward to contributing more!
=> Fix minor typo

src/ir/from_ast/astconv.rs
Fixes #204. Fixes instance declaration in `astconv.rs` to generate missing optional parameters.
=> fix optional parameter generation

src/ir/utils.rs
Adds a `find()` function for DenseIndexInfo that returns a `Some` if the given index is in the mapping and `None` if not. Intended for use in monomorphization, but probably also generally useful.
closes #229
=> Add find() function for DenseIndexInfo

src/ir/comp.rs, src/ir/control.rs, src/ir/expr.rs, src/ir/from_ast/astconv.rs, src/ir/printer.rs, src/ir/structure.rs, src/ir/utils.rs, src/ir_passes/lower/build_ctx.rs, src/ir_passes/lower/compile.rs
Mostly makes the printer use the `Info` data to print out components so that they better match their source-level representation and removes `std::fmt` implementations from IR nodes. The IR printer should be the only way to print meaningful values from the IR.
=> [NFC] Some IR cleanup

src/ir/comp.rs, src/ir/expr.rs, tests/ir_check/bundle-delay.expect, tests/ir_check/bundle-mismatch.expect, tests/ir_check/bundle.expect, tests/ir_check/poly-mismatch.expect
Moves basic simplification from the `ExprIdx` smart constructors into the `Ctx` `add` function instead.
=> Add simplification for expressions upon addition

Cargo.toml, src/ir/comp.rs, src/ir/from_ast/astconv.rs, src/ir/info.rs, src/ir/mod.rs, src/ir/printer.rs, src/ir_passes/discharge.rs, src/ir_passes/interval_check.rs, src/ir_passes/lower/compile.rs, src/ir_passes/type_check.rs
Adds struct variants to the info struct and defines conversion functions that panic when incorrect.
Requested from https://github.com/cucapra/filament/pull/238#discussion_r1276280429
This should probably be merged before #233 is worked on.
=> Change info struct to use struct variants.

src/ir_passes/build_domination.rs, src/ir_passes/mod.rs, src/ir_visitor/visitor.rs, src/main.rs
Builds the domination invariant for the IR where instances are defined before invocations, which are defined before connections. Does this by hoisting all instances to the top of the scope followed by invocations. Everything else is left in place.
=> pass to build domination invariant

src/ir/expr.rs, src/ir/idxs.rs, src/ir/printer.rs, src/ir_passes/assignment_check.rs, src/ir_passes/bundle_elim.rs, src/ir_passes/lower/build_ctx.rs, src/ir_passes/lower/compile.rs, src/ir_passes/lower/utils.rs
A bunch of places in the code base use `as_concrete` and immediately unwrap it which leads to hard to read error messages. This instead defines a `concrete` method on `ExprIdx` that uses `internal_error` to signal better errors when problems occur.
=> Limit uses of `as_concrete`

src/cmdline.rs, src/ir_passes/assignment_check.rs, src/ir_passes/assume.rs, src/ir_passes/build_domination.rs, src/ir_passes/bundle_elim.rs, src/ir_passes/discharge.rs, src/ir_passes/hoist_facts.rs, src/ir_passes/interval_check.rs, src/ir_passes/prop_simplify.rs, src/ir_passes/type_check.rs, src/ir_visitor/visitor.rs, src/main.rs, src/utils/macros.rs, src/utils/mod.rs
Adds a bunch of macros to clean up the pass specification process and replaces the `--show-ir` flag with `--dump-after` which allows us to control exactly which pass to print out information after. Additionally, the macro for pass specification tracks the amount of time each pass took at `--log info`.
=> Macro for pass pipeline specification

fil-derive/src/lib.rs, src/ir/comp.rs, src/ir/context.rs, src/ir/ctx.rs, src/ir/expr.rs, src/ir/fact.rs, src/ir/from_ast/astconv.rs, src/ir/idxs.rs, src/ir/mod.rs, src/ir/structure.rs, src/ir/subst.rs, src/ir/time.rs, src/ir/utils.rs, src/ir_passes/assume.rs, src/ir_passes/bundle_elim.rs, src/ir_passes/hoist_facts.rs, src/ir_passes/interval_check.rs, src/ir_passes/mono/monodeferred.rs, src/ir_passes/mono/monosig.rs, src/ir_passes/prop_simplify.rs, src/ir_passes/type_check.rs
Fixes #261 and also generalizes some existing functions to use `Ctx` instead of `Component`
=> Implement Ctx for Foreigns.

fil-derive/src/lib.rs, src/ir/comp.rs, src/ir/context.rs
Fixes #291. This also generated way better error message because we're using the `Parse` which is idiomatic for the `syn` trait.
=> Use compact syntax for the `Ctx` derive macro

src/cmdline.rs, src/ir_passes/discharge.rs
Fixes #320. It seems like too much work to make the hack mentioned in the issue work because we would have to declare the sexpr in the easy_smt context. 
CVC5 authors said that this is a valid behavior of the solver so we're falling back on using the older parameter strings when using cvc5 (https://github.com/cvc5/cvc5/issues/9998).
=> Choose parameter SExp based on solver

aetherling/conv2d_1/shim.fil, aetherling/conv2d_144/shim.fil, aetherling/conv2d_16/shim.fil, aetherling/conv2d_2/shim.fil, aetherling/conv2d_4/shim.fil, aetherling/conv2d_48/shim.fil, aetherling/conv2d_8/shim.fil
The original implementations were asserting the exact values of the parameters which is unnecessary.
=> Simplify aetherling module signatures

fil-ir/src/expr.rs, fil-ir/src/fact.rs
The goal was to make it so that `hoist-facts` only adds relevant terms to the path condition of an assertion but that requires a recursive implementation because whenever a variable is marked as relevant, all clauses that use it also need to have all their variables declared as relevant.
=> Methods to compute relevant vars in exprs and props

fil-ir/src/printer/comp.rs, src/ir_passes/hoist_facts.rs, src/ir_passes/interval_check.rs, tests/check/scope-invoke-check.expect, tests/check/scope-invoke-check.fil
Previously we were asserting facts about invoke arguments in the top-level scope which means that the path condition was not getting added correctly. This is problematic when we need to fundamentally rely on a particular assumption to make the check succeed.
=> Ensure constraints on invoke are asserted in the right scope

fil-ir/src/from_ast/astconv.rs, fil-ir/src/from_ast/build_ctx.rs, fil-ir/src/info.rs, fil-ir/src/printer/display_ctx.rs, fil-ir/src/structure.rs, fil-ir/src/validate.rs, src/ir_passes/bundle_elim.rs, src/ir_passes/interval_check.rs, src/ir_passes/mono/monosig.rs
The `idx` field was previously always required for `Liveness` which added a lot of unused parameters and assumptions for those parameters. This makes the `idx` field optional which does make the code less clean but I think is overall worth it.
=> Make `idx` in liveness optional in ports

fil-ir/src/comp.rs, fil-ir/src/from_ast/astconv.rs, fil-ir/src/printer/comp.rs, src/ir_passes/interval_check.rs, src/ir_passes/type_check.rs
Adds tracking for parameters, events, and their assertions. The former two are tracked in a separate field because we need to store them in program order. Perhaps in the future we can make the IR track by name assignments to both parameters and events.
=> Track more things in the component signature

fil-ir/src/from_ast/astconv.rs, fil-ir/src/from_ast/build_ctx.rs, fil-ir/src/info.rs, fil-ir/src/printer/display_ctx.rs, fil-ir/src/structure.rs, fil-ir/src/validate.rs, src/ir_passes/bundle_elim.rs, src/ir_passes/interval_check.rs, src/ir_passes/mono/monosig.rs
Turns out even bundles with liveness that doesn't use the index parameter in the type needs the parameter to encode the length constraints so functionally, this is not useful to do.
=> Revert "Make `idx` in liveness optional in ports (#359)"

src/cmdline.rs, src/ir_passes/discharge.rs
Fixes #374. This uses the encoding from the issue and instantiates both parameters and events as bitvectors and adds assertions to eliminate overflow.
=> Bitvector encoding for proofs

fil-ir/src/from_ast/astconv.rs
=> Fixes bug in astconv where ifs are evaluated without pushing a scope

doc/docs/lang/tutorial.md, web/templates/index.html
I've been fixing typos as I read the documentation.
I'm taking my first class on hardware design this semester. I'm very new to it. It hasn't been too difficult understanding hardware concurrency, but I don't understand at all how computer engineers pipeline modules and match the timings and delays between them. If an engineer were to work with a large number of modules, it would become very difficult to keep track of signal validity between them.
I really like the solution that filament provides in response to the issue! This is a really cool piece of software.
=> Fix typos in documentation

Dockerfile
Filament wasn't building before because we needed to update the Rust version. I just changed the Dockerfile to use a newer version of the Calyx Dockerfile
=> Bump Calyx docker image

fil-ir/src/from_ast/astconv.rs, tests/check/borrow.fil, tests/errors/typecheck/borrow.expect, tests/errors/typecheck/borrow.fil
Closes #419 
Ended up being a little tweak in `astconv`. When we initially construct the `ir::Instance`, I had it use an empty `Vec` for the `lives` field, and then fill it in after we've already made the source-level name to idx binding in the ctx. This will let us use an instance's existential parameters in its borrow range.
Also adds two small tests, one where it typechecks and one where it doesn't because there aren't any constraints on the existential parameter.
=> Instance borrow ranges can reference instance

primitives/state.fil
Made a silly mistake that I didn't catch in the other PR, didn't realize you need to do `a{0..N} = b{0..N}` instead of just `a = b` when doing bundle assignments.
=> Fix shift reg indices

Cargo.toml, src/main.rs
We should start generate `static` components with the Calyx backend so that Calyx components can start interfacing and consuming Filament-generated code
=> Bump to latest Calyx version

crates/ast/src/constraint.rs, crates/ast/src/expr.rs, crates/ast/src/parser.rs, crates/ast/src/syntax.pest, crates/filament/src/ir_passes/discharge.rs, crates/filament/src/ir_passes/lower/utils.rs, crates/filament/src/ir_passes/mono/monodeferred.rs, crates/filament/src/ir_passes/mono/monosig.rs, crates/ir/src/comp.rs, crates/ir/src/control.rs, crates/ir/src/expr.rs, crates/ir/src/fact.rs, crates/ir/src/from_ast/astconv.rs, crates/ir/src/printer/expr.rs, crates/ir/src/printer/prop.rs, crates/ir/src/time.rs, crates/ir/src/utils/subst.rs, tests/check/if-expr.fil
Adds if-expressions, closes #436. Each arm of the if currently must be a simple expression; could be extended in a future PR to support blocks of commands that return an expression, if necessary. 
Represented in the IR as another member of `ir::Expr` that takes a condition (`ir::Prop`) and two expressions. This worked pretty okay, just had to do some reshuffling of code in the monomorphize pass to be able to handle `Prop`s at the same time we handle `Expr`s. 
One sort of weird thing happens in `Discharge`, where we need to convert the if's condition (a `Prop`) to an `SExp` as we are converting all of a component's `Expr`s, which happens before we do the rest of the component's `Prop`s. This means that we need to push things to `Discharge::prop_map` out of order, which means that `SExpr` …
=> Add simple if-exprs

Dockerfile
Current setup means fud will only run in the filament home directory.
=> Use full path for filament target in fud configuration

.gitattributes
Because `runt` uses `LF` instead of `CRLF` line endings, certain tests that for some reason have `CRLF` endings are failing. this should fix the issue.
=> Set up .gitattributes to change line endings to `LF`

crates/ast/src/attribute.rs, crates/ast/src/component.rs, crates/ast/src/parser.rs, crates/filament/src/ast_passes/mod.rs, crates/filament/src/ast_passes/toplevel.rs, crates/filament/src/ast_visitor/mod.rs, crates/filament/src/ast_visitor/visitor.rs, crates/filament/src/cmdline.rs, crates/filament/src/ir_passes/fsm_attributes.rs, crates/filament/src/lib.rs, crates/filament/src/macros.rs, crates/filament/src/main.rs
Adds a component attribute allowing the user to specify a toplevel component other than `main`. If not specified, `main` is retained as the default toplevel component. To do this, it re-introduces AST Passes through an AST Visitor, and implements the same macros as ir passes for generating pass pipelines.
Errors are thrown if:
* Multiple toplevel components are specified
* An extern is specified as a toplevel component
=> Add AST Passes and the #[toplevel] attribute.

crates/ast/src/control.rs, crates/ast/src/parser.rs, crates/ast/src/syntax.pest, crates/filament/src/ir_passes/build_domination.rs, crates/filament/src/ir_passes/discharge.rs, crates/filament/src/ir_passes/mono/monodeferred.rs, crates/ir/src/control.rs, crates/ir/src/from_ast/astconv.rs, crates/ir/src/printer/comp.rs, crates/ir/src/structure.rs, crates/ir/src/validate.rs, tests/errors/binding/let-unbound.expect, tests/errors/binding/let-unbound.fil
Adds syntax to the frontend for `let param = ?;` let bindings. Currently these will error out during monomorphization as there is no binding.
=> add `let = ?` binding for temporary Filament automation frontend

crates/filament/src/ir_passes/bundle_elim.rs, crates/ir/src/utils/sparse_info.rs
Essentially a one line fix that makes new ports generated by bundle-elim have no parameters.
=> Fixes `bundle-elim` leaving references to deleted parameters

crates/filament/src/ir_passes/mono/monosig.rs
=> add proper bundle param infos to monomorphize

crates/filament/src/ir_passes/lower/compile.rs
Turns out setting the `toplevel` attribute is not enough for calyx, and we need to explicitly set an entrypoint.
=> Fix entrypoint setting with calyx

apps/blas/.gitignore, apps/blas/run.sh, apps/blas/util.py, runt.toml
Blas tests in `runt.toml` defaults to python which on some systems uses python2.7.
=> Use python3 in blas testing instead of python

crates/ast/src/control.rs, crates/ast/src/parser.rs, crates/ast/src/syntax.pest, crates/filament/src/ir_passes/bundle_elim.rs, crates/filament/src/ir_passes/mono/monosig.rs, crates/filament/src/ir_passes/mono/utils/comp.rs, crates/ir/src/comp.rs, crates/ir/src/from_ast/astconv.rs, crates/ir/src/structure.rs, crates/utils/src/attr/mod.rs, crates/utils/src/attr/types.rs, crates/utils/src/lib.rs, crates/utils/src/macros.rs
Adds port attributes of the form
```
#[attrib]
port: ['G, 'G+1] 32,
...
```
Also can technically be used within bundle definitions like
```
bundle #[attrib] bun[3]: for<i> ['G + i, 'G+i+1] 32;
```
=> Port attributes

apps/blas/util.py, crates/filament/src/ir_passes/discharge.rs, runt.toml
Fixes #487 
Also splits `check` tests into `cvc5` and `z3` to prevent things like this from occurring again. The existing `if-expr` test already checks this but was just never run on `cvc5`.
=> Prevent double-definitions of propositions

README.md
The "tutorial" link actually links to the main website rather than the docs which have the tutorial.
=> Update link to tutorial in README.md

doc/docs/start.md
The instruction suggest using a file that no longer exists. I tested this file and it works.
Fixes #451
=> Fix getting started instructions

doc/docs/start.md
=> Fix link in Getting Started docs

crates/filament/src/cmdline.rs, crates/filament/src/macros.rs, crates/filament/src/main.rs
Add `--dump-all` to dump the state of the AST after every pass and invert the `preserve-names` option.
=> Update CLI opts

crates/filament/src/ir_visitor/visitor.rs, crates/ir/src/validate.rs
Strengthens the validation pass to check exprs, params, etc and also has it run by default after every IR pass.
Seems to have minimal performance hit.
=> Strengthens the validation pass
