cucapra/filament

src/bind_check.rs
src/event_checker/ast.rs
src/interval_checking/checker.rs
src/interval_checking/context.rs
src/interval_checking/mod.rs
src/interval_checking/solver.rs
tests/errors/dynamic-share.expect
tests/errors/share-range.expect
tests/errors/share-range.fil

Instance sharing check

---

evaluation/floating-point/add/fp-add.fil
evaluation/iterative-divider/iter-div.fil
primitives/core.fil
primitives/core.sv
primitives/signed.fil
src/bind_check.rs
src/core/control.rs
src/core/mod.rs
src/core/signature.rs
src/core/time_rep.rs
src/event_checker/ast.rs
src/event_checker/check.rs
src/frontend/ast.rs
src/frontend/parser.rs
src/frontend/syntax.pest
src/interface_infer/infer.rs
src/interval_checking/checker.rs
src/interval_checking/context.rs
src/visitor/binding.rs
tests/check/max.fil
tests/check/merge.fil
tests/compile/par.fil
tests/compile/pipeline-with-ii-1.fil
tests/compile/simple-alu.fil
tests/compile/window-sum.fil
tests/errors/unprovable-cons.fil
tests/errors/user-level-constraint.fil

Add default event bindings

---

src/backend/compile.rs
src/binding/comp.rs
src/binding/prog.rs
src/core/component.rs
src/core/control.rs
src/core/mod.rs
src/frontend/parser.rs
src/frontend/syntax.pest
src/passes/monomorphize.rs
src/utils/solver.rs
src/visitor/checker.rs
src/visitor/visit.rs
tests/errors/bundle.expect
tests/errors/bundle.fil

Currently does not check that the access into the bundle is within bound. This would be necessary for correct compilation.

Add `bundle` syntax and some checking for it

---

src/backend/compile.rs
src/binding/comp.rs
src/core/constraint.rs
src/core/control.rs
src/core/loc.rs
src/core/mod.rs
src/frontend/parser.rs
src/frontend/syntax.pest
src/passes/bind_check.rs
src/passes/bundle_elim.rs
src/passes/interval_checking/checker.rs
src/passes/lower.rs
src/passes/monomorphize/rewriter.rs
tests/errors/bundle-mismatch.expect
tests/errors/bundle-mismatch.fil
tests/errors/bundle.expect

- generalize port accesses
- even more errors
- ranges over bundle ports

Generalize ports

---

src/passes/bundle_elim.rs

Fix for bundle accesses by removing unnecessary assertion.

remove range access assertion

---

src/binding/invoke.rs
tests/check/resolve-expr-first.fil

@UnsignedByte this should fix the problem you were running into!

Resolve exprs first

---

src/ast/expr.rs
src/ast/implication.rs
tests/check/assume-pow2.fil

Added quick test for auto assumption compilation, also added more automatic assumptions to cover base cases.

Small feature update for auto assumptions

---

src/ir/comp.rs
src/ir/expr.rs
src/ir/fact.rs
src/ir/from_ast/astconv.rs
src/ir/idxs.rs
src/ir/utils.rs
src/ir_passes/hoist_facts.rs
src/ir_passes/mod.rs
src/ir_visitor/mod.rs
src/ir_visitor/visitor.rs
src/lib.rs
src/main.rs
tests/compile/ir/comb.expect
tests/compile/ir/deserialize.expect
tests/compile/ir/param-if.expect
tests/compile/ir/param-mac.expect
tests/compile/ir/param-moving-sum.expect
tests/compile/ir/phantom-pipeline.expect
tests/compile/ir/pipeline-with-ii-1.expect
tests/compile/ir/reduction-tree.expect
tests/compile/ir/serialize.expect

- ir visitor
- path cond
- pass complete
- working

Pass to hoist fact to top-level

---

src/ast/signature.rs
src/ir/comp.rs
src/ir/control.rs
src/ir/expr.rs
src/ir/fact.rs
src/ir/from_ast/astconv.rs
src/ir/from_ast/build_ctx.rs
src/ir/mod.rs
src/ir/printer.rs
src/ir/structure.rs
src/ir/time.rs
src/ir/utils.rs
src/ir_passes/interval_check.rs
src/ir_passes/mod.rs
src/ir_visitor/visitor.rs
src/main.rs

- add event constraints from sig
- add asserts from invokes

Track and add event constraints

---

Cargo.toml
runt.toml
src/ir_passes/discharge.rs
src/ir_passes/hoist_facts.rs
src/ir_passes/mod.rs
src/ir_visitor/visitor.rs
src/main.rs

Pass that discharges assert statements using an SMT solver

Pass to discharge assumptions

---

src/ir/from_ast/astconv.rs
src/ir/info.rs
src/ir/structure.rs

Adds unannotated ports and interface ports to the IR.

Unannotated and Interface ports for IR

---

src/ir/from_ast/astconv.rs

Quick fix using `zip_longest` for generating event binds given optional events.
Resolves #201.

Fix eventbinding generation

---

src/ir/comp.rs
src/ir/from_ast/astconv.rs
src/ir/printer.rs
src/ir/structure.rs
src/ir/subst.rs
src/ir_passes/interval_check.rs

The #216 PR has a bunch of changes that will generally affect other PRs (like lowering) so I'm extracting them out here. @gabizon103 this will affect your PR. Hopefully merging with main should be sufficient.

Extract useful changes from the mono PR

---

src/ir/from_ast/astconv.rs
src/ir/info.rs
src/ir/structure.rs

Changes the representation as discussed with @rachitnigam

Updates the interface port implementation

---

src/ir/comp.rs
src/ir/fact.rs
src/ir/subst.rs
src/ir/time.rs

Simplify propositions upon component addition

---

src/ir/utils.rs

Dense index out of order pushes

---

evaluation/fuzz/check.sh

Should be merged to enable evaluation tests in #216

Adds an ir option for check.sh

---

src/cmdline.rs
src/ir/info.rs
src/ir_passes/bundle_elim.rs
src/ir_passes/lower/build_ctx.rs
src/ir_passes/lower/compile.rs
src/ir_passes/lower/fsm.rs
src/ir_passes/lower/utils.rs
src/main.rs

Adds a flag to use infos to generate names during compilation.

Enable preservation of compiled names.

---

Cargo.toml
src/ir_passes/lower/compile.rs
src/ir_passes/lower/fsm.rs
src/ir_passes/lower/utils.rs
src/main.rs

Bump version of `calyx` crates and use `guard!` macro

---

src/cmdline.rs
src/ir_passes/discharge.rs
src/ir_visitor/visitor.rs

Add discharge pass flag

---

fil-ir/src/printer/comp.rs
fil-ir/src/printer/display_ctx.rs
fil-ir/src/printer/expr.rs
fil-ir/src/printer/mod.rs
fil-ir/src/printer/prop.rs
src/ir_passes/mono/utils/comp.rs

Some cleanup of the printing code.

Printer revamp

---

fil-ir/src/comp.rs
runt.toml
src/ir_passes/interval_check.rs
tests/check/exist-sig-assume.expect
tests/check/exist-sig-assume.fil

Signature assertions can assume existential constraints

---

web/templates/index.html

webpage link to frisc

---

examples/tut-pipe-wrong-1.expect
examples/tut-pipe-wrong-2.expect
examples/tut-pipe-wrong-3.expect
examples/tut-wrong-1.expect
examples/tut-wrong-2.expect
fil-ir/src/info.rs
src/ir_passes/interval_check.rs
src/ir_passes/mono/monosig.rs
tests/errors/binding/already-bound.expect
tests/errors/bundle/bundle-mismatch.expect
tests/errors/bundle/bundle.expect
tests/errors/bundle/multi-bad-access.expect
tests/errors/bundle/multi-liveness.expect
tests/errors/phantom-check/event-bind.expect
tests/errors/typecheck/poly-mismatch.expect
tests/errors/typecheck/unprovable-cons.expect
tests/errors/typecheck/unsatisfied-guarantee.expect
tests/errors/typecheck/unsatisfied-requirement.expect
tests/run/misaligned-reuse.fil

Change the error message when the signal is not alive for the right amount of time.

Change liveness error message

---

web/templates/index.html

fix typo in website

---

.github/workflows/test.yml
Dockerfile

The newest version of flopoco has DSP inference, so we are updating to it in order to possibly improve some of our results.

Update flopoco to latest

---

apps/blas/util.py

Somehow the shebang added in the last PR was lost.

Add shebang to utils py

---

crates/ast/src/parser.rs
crates/filament/src/ast_passes/toplevel.rs
crates/ir/src/printer/comp.rs
crates/utils/src/attr/attributes.rs
crates/utils/src/attr/store.rs
crates/utils/src/macros.rs

Add attribute displaying to IR printer

---

doc/docs/start.md

Update fud links in Getting Started docs
